travis:
  secure:
    BINSTAR_TOKEN: NUxOZgBWO3cplPiMuOgfnJ7JecZoLTD2yPnqyXx5J+koSfm0sd10iNIRqoPbxKkMjIvfS38F8XLYIg9tars3id7S+J8QZFvIb0rEYE4rgxWV+uiDO0WaMJubIZNUU23w5vPy7eZ0kwGDD5gd+qpTggWnkJYvmfrSR3D+FFBq2xbFH8qj+4TSASMx6fhWnmWRqt7Y6axhc4u+2r2KLdFqo+28O82OaE+94mZrip16jMu6dwIW3cNAEoQetotmXoqAuyrCaevpVohjbyKih1z9pdvOmCYLzngbEXQXMR0ojg2djc6w89N0V5A3wVtJjkau81LqlRHJj3PS/5UjZgs910Q2Kyu3WA4hk7ZCQjz1HcQkNU350FaUOZSoSWaH0Oi53pYjJeI9En3gZAa338wpY00CjcvvEy4PChD9BFmX/cojpoe0eVRNh2P4H8OOpQC1v66DCA/TbSoFf5p2RMz1qE4yv++kbupqUzV0PTbxyTU3xiVEa4u+VUqMWUyUV48uRCXOIlAKZCkiPeyFwb56qSF0aD3V1wKk9+epGDVScQy8r+hsEx+0u+JWmxe3YF0eor1JRE1zRdIjzVHpcSUFBOXbrnJi4lDal3CQ5LH0iy0IM19ENXQP1CuR0215nNGimGLoqdTa2EUnMxuFFfGuU34gpBiNJ0CBV8cst3ULTjQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
